### PR TITLE
Fix proto gen for mac

### PR DESCRIPTION
**Pull request by sid42**
Can someone with mac machine try the `make gen-mac` command and see it works as expected?

### CODE REVIEW

**Comment by Shreyas15srivatsa** [comment]
GGWP

**Review by Shreyas15srivatsa — APPROVED** [review]

**Review by KnotScientific — APPROVED** [review]
💯

**Review by babrar — CHANGES_REQUESTED** [review]
I still face the issues outlined by @madhur4444.
`make gen-mac` created `streamer_pb2_grpc.py` with syntax errors.
```py
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . 0  //  <-- syntax error!


class StreamerStub(object):
    """Missing associated documentation comment in .proto file."""
```

Could be a M1 thing. Blocking approval till @madhur4444 approves it.

**Comment by sid42** [comment]
- `brew install gnu-sed`

**Comment by babrar** [comment]
big brain

**Review by babrar — APPROVED** [review]

**Review by KnotScientific — APPROVED** [review]
Confirmed working on m1 mac with witnesses
image

**Pull request merged**
